KN-#699bI3vZ: setup  project
kinyarwanda-net/mobile-app pull request #2
Opened 2020-01-24 09:07 UTC by sengayire

delivers(chore): #699bI3vZ

#### What does this PR do?
- Install require packages and libraries
- Organize folder structure
#### Description of Task to be completed?
- Test environment
- Folder structure
#### How should this be manually tested?
- Clone the repo locally 
- once cloned go to cloned repo
-  In terminal type ```npm i ``` to install required packages
- Run ```npm start  ```or expo start to start expo metro bundler
- Run ```i`` to start the app in ```ios``` emulator or ```a``` from android
- Or scan the provided QRCode in metro bundler to run the app in physical devices``` you should have expo installed in your device``` 
-start using  the app
#### Any background context you want to provide?
- N/A
#### What are the relevant Trello stories?
- [#699bI3vZ](https://trello.com/c/699bI3vZ/4-setup-a-react-native-app)
#### Screenshots (if appropriate)
- NA
#### Questions:
- N/A

2020-01-24 13:45 UTC, nzuwera requested changes
use the latest lts stable node image: circleci/node:12.14.1

2020-01-26 19:15 UTC, nzuwera approved these changes

2020-01-27 13:29 UTC, djallas commented
@prince Can you fix splash screen on Android. It doesn't fit the screen.

2020-01-27 16:07 UTC, kagaramag approved these changes

2020-01-28 04:42 UTC, merged